/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gui;

import javax.swing.JOptionPane;

import br.com.bo.VerificaUltimaReleasesFiliais;
import br.com.constantes.ConstanteIpLojas;
import br.com.utilitarios.Conecta;

/**
 *
 * @author wev
 */
public class FAmbienteTeste extends javax.swing.JDialog {

	/**
	 * Creates new form FAmbienteTeste
	 */
	public FAmbienteTeste(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLojas = new javax.swing.JLabel();
        jComboBoxLojas = new javax.swing.JComboBox();
        jRadioButtonRelease = new javax.swing.JRadioButton();
        jRadioButtonDeploy = new javax.swing.JRadioButton();
        jTextFieldAtual = new javax.swing.JTextField();
        jLabelAtual = new javax.swing.JLabel();
        jScrollPaneLogs = new javax.swing.JScrollPane();
        jTextAreaLogs = new javax.swing.JTextArea();
        jToggleButtonExecutar = new javax.swing.JToggleButton();
        jToggleButtonSair = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Amientes de Teste Jap"));

        jLabelLojas.setText("Abiente de Teste :");

        jComboBoxLojas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 - Cartão Paraiba Frente Loja (CENTRAL)", "2 - Cartão Paraiba Frente Loja (FILIAL)", "3 - Teste Jap (Central)", "4 - Teste Jap (Filial)", "5 - Teste de Migração (Central)", "6 - Teste de Migração (BNV)", "7 - Teste de Migração (STI)" }));

        jRadioButtonRelease.setText("Release");

        jRadioButtonDeploy.setText("Deploy");

        jTextFieldAtual.setEditable(false);

        jLabelAtual.setText("Release Teste");

        jTextAreaLogs.setEditable(false);
        jTextAreaLogs.setColumns(20);
        jTextAreaLogs.setRows(5);
        jTextAreaLogs.setBorder(javax.swing.BorderFactory.createTitledBorder("Logs "));
        jScrollPaneLogs.setViewportView(jTextAreaLogs);

        jToggleButtonExecutar.setText("Executar");
        jToggleButtonExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonExecutarActionPerformed(evt);
            }
        });

        jToggleButtonSair.setText("Sair");
        jToggleButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLojas)
                    .addComponent(jLabelAtual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxLojas, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonRelease)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jRadioButtonDeploy)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButtonExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jScrollPaneLogs)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jToggleButtonExecutar, jToggleButtonSair});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLojas)
                    .addComponent(jComboBoxLojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonRelease)
                    .addComponent(jRadioButtonDeploy))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAtual)
                    .addComponent(jToggleButtonExecutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneLogs, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jToggleButtonSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButtonSairActionPerformed
		// TODO add your handling code here:
		this.setVisible(false);
	}// GEN-LAST:event_jToggleButtonSairActionPerformed

	private void jToggleButtonExecutarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButtonExecutarActionPerformed
		Conecta conecta = new Conecta();
		VerificaUltimaReleasesFiliais verificaReleases = new VerificaUltimaReleasesFiliais();
		ConstanteIpLojas ip = new ConstanteIpLojas();
		char op = jComboBoxLojas.getSelectedItem().toString().charAt(0);
		String ipLojas = ip.lojasEndereco(String.valueOf(op));

			if (jRadioButtonDeploy.isSelected() && jRadioButtonRelease.isSelected()) {
				this.jTextFieldAtual.setText(verificaReleases.verRelease(ipLojas,1));

			} else if (jRadioButtonDeploy.isSelected()) {
				this.jTextFieldAtual.setText(verificaReleases.verRelease(ipLojas, 1));
//				jTextAreaLogs.setText("Executando Deploy " + ipLojas );

			} else if (jRadioButtonRelease.isSelected()) {
				this.jTextFieldAtual.setText(verificaReleases.verRelease(ipLojas, 1));
//				jTextAreaLogs.setText("Executando Release : " + ipLojas);

			} else {
				JOptionPane.showMessageDialog(null, "Você Tem que informar Deploy ou Release!");
			}

	}// GEN-LAST:event_jToggleButtonExecutarActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FAmbienteTeste.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FAmbienteTeste.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FAmbienteTeste.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FAmbienteTeste.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				FAmbienteTeste dialog = new FAmbienteTeste(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxLojas;
    private javax.swing.JLabel jLabelAtual;
    private javax.swing.JLabel jLabelLojas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonDeploy;
    private javax.swing.JRadioButton jRadioButtonRelease;
    private javax.swing.JScrollPane jScrollPaneLogs;
    private javax.swing.JTextArea jTextAreaLogs;
    private javax.swing.JTextField jTextFieldAtual;
    private javax.swing.JToggleButton jToggleButtonExecutar;
    private javax.swing.JToggleButton jToggleButtonSair;
    // End of variables declaration//GEN-END:variables
}
