/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gui;

import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import br.com.bo.ExecutaDeploy;
import br.com.bo.VerificaUltimaReleasesFiliais;
import br.com.constantes.TodasAsLojas;

/**
 * 
 * @author WevKleyton
 *
 */
public class FDesploy extends javax.swing.JFrame {

    /**
     * Creates new form FDesployRelease
     */
    public FDesploy() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDeploy = new javax.swing.JPanel();
        jLabelDeploy = new javax.swing.JLabel();
        jComboBoxLojas = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jButtonDeploy = new javax.swing.JButton();
        jButtonGetRelease = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelDeploy.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelDeploy.setLayout(new javax.swing.BoxLayout(jPanelDeploy, javax.swing.BoxLayout.LINE_AXIS));

        jLabelDeploy.setText("Lojas :");
        jPanelDeploy.add(jLabelDeploy);

        jComboBoxLojas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "172.16.40.237", "TODAS", "IGM", "NRE", "SDN", "VMR", "JAC", "SLL", "ABA", "RED", "COA", "TCM", "TAL", "MJU", "STI", "BNV", "RBC", "BCN", "VDE", "BGC", "AMT", "SAT", "PAP", "PAG", "TUB", "MAR", "ARG", "GUR", "PTO", "CUP", "EDC", "PNA", "SFX", "VIR", "CDC", "ITU", "CAP", "TMC", "RMO", "CPO", "PAF", "ANN", "SDA", "RBV", "PAM", "WAD", "MIT", "BAO", "XIG", "XAB", "FOA", "TOC", "SAA" }));
        jPanelDeploy.add(jComboBoxLojas);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButtonDeploy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/resources/deploy-icon_text_24x24.png"))); // NOI18N
        jButtonDeploy.setMnemonic('d');
        jButtonDeploy.setText("Deploy");
        jButtonDeploy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeployActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeploy);

        jButtonGetRelease.setText("Get_Release");
        jButtonGetRelease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetReleaseActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGetRelease);

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLimpar);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/resources/icon_6692_24x24.png"))); // NOI18N
        jButtonSair.setMnemonic('s');
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSair);

        jTextAreaLog.setEditable(false);
        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jTextAreaLog.setBorder(javax.swing.BorderFactory.createTitledBorder("Log"));
        jScrollPane1.setViewportView(jTextAreaLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDeploy, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDeploy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
//    	this.setVisible(false);
    	dispose();

    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonDeployActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeployActionPerformed
        // TODO add your handling code here:
    	TodasAsLojas tlojas = new TodasAsLojas();
    	ExecutaDeploy executaDaploy = new ExecutaDeploy();
		ArrayList<String> lojas = tlojas.ListaLojas();
		String saida;
		if (jComboBoxLojas.getSelectedItem().toString() == "TODAS"){
			for (int i = 0; i < lojas.size(); i++) {
//			String loja = lojas.get(i);
				saida = executaDaploy.deploy(lojas.get(i));
				jTextAreaLog.setText(saida);
			}
			
		}else{
			String loja = jComboBoxLojas.getSelectedItem().toString();
			saida = executaDaploy.deploy(loja);
			jTextAreaLog.setText(saida);
			
		}
    	
    }//GEN-LAST:event_jButtonDeployActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
    	jTextAreaLog.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonGetReleaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetReleaseActionPerformed

    }//GEN-LAST:event_jButtonGetReleaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDesploy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDesploy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDesploy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDesploy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FDesploy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeploy;
    private javax.swing.JButton jButtonGetRelease;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBoxLojas;
    private javax.swing.JLabel jLabelDeploy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDeploy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaLog;
    // End of variables declaration//GEN-END:variables
}
