/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gui;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author WevKleyton
 *teste de commit
 *ajuste de form
 */
public class FPrincipal extends javax.swing.JFrame {

	/**
	 * Creates new form FPrinci
	 * pal
	 * teste de apreendizado 
	 */
	public FPrincipal() {
		initComponents();
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarSair = new javax.swing.JMenuBar();
        jMenuSistema = new javax.swing.JMenu();
        jMenuItemRelease = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuUtils = new javax.swing.JMenu();
        jMenuItemEnviaArquivos = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuSistema.setMnemonic('i');
        jMenuSistema.setText("Sistema");

        jMenuItemRelease.setMnemonic('r');
        jMenuItemRelease.setText("Release");
        jMenuItemRelease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReleaseActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuItemRelease);
        jMenuSistema.add(jSeparator1);

        jMenuItem1.setMnemonic('a');
        jMenuItem1.setText("Ambientes de Teste");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTesteActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuItem1);

        jMenuItem2.setMnemonic('b');
        jMenuItem2.setText("Bakup");
        jMenuSistema.add(jMenuItem2);

        jMenuBarSair.add(jMenuSistema);

        jMenuUtils.setMnemonic('u');
        jMenuUtils.setText("Utils");

        jMenuItemEnviaArquivos.setMnemonic('e');
        jMenuItemEnviaArquivos.setText("Envia Arquivos");
        jMenuItemEnviaArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEnviaArquivosActionPerformed(evt);
            }
        });
        jMenuUtils.add(jMenuItemEnviaArquivos);

        jMenuBarSair.add(jMenuUtils);

        jMenuSair.setMnemonic('s');
        jMenuSair.setText("Sair");

        jMenuItemSair.setMnemonic('s');
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBarSair.add(jMenuSair);

        setJMenuBar(jMenuBarSair);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemReleaseActionPerformed(java.awt.event.ActionEvent evt) {                                                  
    	FRelease newRelease = new FRelease(this, true);
    	newRelease.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
    	newRelease.setTitle("Gera Releases");
    	newRelease.setLocationRelativeTo(null);
    	newRelease.setResizable(false);
    	newRelease.setVisible(true);
    }                                                

    private void jMenuItemEnviaArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEnviaArquivosActionPerformed
        // TODO : Chama Frame Envia Arquivos
    	FEnviaArquivos enviArquivos = new FEnviaArquivos();
    	enviArquivos.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemEnviaArquivosActionPerformed

    private void jMenuItemTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTesteActionPerformed
        // TODO : Chama Frame Para Ambientes de Teste

    	FAmbienteTeste ambienteTeste = new FAmbienteTeste(this, true);
        ambienteTeste.setLocationRelativeTo(null);
        ambienteTeste.setVisible(true);
    }//GEN-LAST:event_jMenuItemTesteActionPerformed
//
//	@SuppressWarnings("unused")

	private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO : Sair de APP
		int returno = JOptionPane.showConfirmDialog(null, "Deseja Relamente Sair","Fechar Sistema" ,JOptionPane.YES_NO_OPTION);
		if (returno == 0){
			System.exit(0);
		}
	}// GEN-LAST:event_jMenuItem2ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FPrincipal().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarSair;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemEnviaArquivos;
    private javax.swing.JMenuItem jMenuItemRelease;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuSistema;
    private javax.swing.JMenu jMenuUtils;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
